### ISSUE TITLE
symbol lookup error: /usr/lib/libatspi.so.0

### ISSUE THREAD

**Issue by AgostinoA** [CyberCircuits/kicad-appimage#1]
./bin/kicad: symbol lookup error: /usr/lib/libatspi.so.0: undefined symbol: g_once_init_leave_pointer

I have this problem with archlinux

**Comment by Grinkers** [comment]
I ran into this on both arch and fedora. It seems there was some incompatible ABI changes in gtk (and potentially many others) between ubuntu 20.04 and later distros. 

#3 should fix this.

**Comment by AgostinoA** [comment]
@CyberCircuits it's a pleasure
