### ISSUE TITLE
KiCad 6 AppImage

### ISSUE THREAD

**Issue by fabianhugo** [CyberCircuits/kicad-appimage#2]
Dear CyberCircuits, 
thanks for this great collection of AppImages.
I would like to create an AppImage of Kicad 6 from my APT repository in Ubuntu 22.04 to move it to Ubuntu 24.04 where no APT repository exists. I did not fully understand if I need an yaml file now, and first tries with 
`bash pkg2appimage KiCad` only created KiCad 4 versions. 
I would like to use KiCad 6 to be able to distribute files with a big compatibility to KiCad versions >6. 
Any help very welcomed.

**Comment by CyberCircuits** [comment]
KiCad 6 is an older version and requires different dependencies.
Please check out v6 [here](https://sourceforge.net/projects/kicad-appimage/files/v6/).
